"""Runtime infrastructure ports."""

from datetime import timedelta
from typing import Protocol

from investment.runtime.domain import EngineEvent, EngineRuntimeState, ResearchJobExecution


class EngineEventPublisher(Protocol):
    def publish(self, event: EngineEvent) -> None: ...


class RuntimeStateRepository(Protocol):
    def save_state(self, state: EngineRuntimeState) -> None: ...
    def save_execution(self, execution: ResearchJobExecution) -> None: ...
    def list_executions(self, limit: int = 100) -> tuple[ResearchJobExecution, ...]: ...
    def get_execution(self, execution_id: str) -> ResearchJobExecution: ...
    def find_execution_by_identity(self, identity: str) -> ResearchJobExecution | None: ...


class JobLock(Protocol):
    def acquire(self, key: str, owner_id: str, ttl: timedelta) -> bool: ...
    def release(self, key: str, owner_id: str) -> bool: ...


class RuntimeScheduler(Protocol):
    def start(self) -> None: ...
    def shutdown(self, *, wait: bool = True) -> None: ...
