"""Persistence boundary for research lifecycle aggregates."""

from typing import Protocol

from investment.crypto.domain.research import (
    BacktestRun,
    DatasetSnapshot,
    Experiment,
    ModelVersion,
    StrategyVersion,
    TrainingRun,
    ValidationRun,
)


class ResearchLifecycleRepository(Protocol):
    def save_experiment(self, experiment: Experiment, *, create: bool = False) -> None: ...
    def get_experiment(self, experiment_id: str) -> Experiment: ...
    def list_experiments(self) -> tuple[Experiment, ...]: ...
    def save_strategy(self, version: StrategyVersion, *, create: bool = False) -> None: ...
    def get_strategy(self, version_id: str) -> StrategyVersion: ...
    def list_strategies(self) -> tuple[StrategyVersion, ...]: ...
    def active_strategy(self, name: str) -> StrategyVersion: ...
    def save_model(self, version: ModelVersion, *, create: bool = False) -> None: ...
    def list_models(self) -> tuple[ModelVersion, ...]: ...
    def save_snapshot(self, snapshot: DatasetSnapshot) -> None: ...
    def get_snapshot(self, snapshot_id: str) -> DatasetSnapshot: ...
    def save_training_run(self, run: TrainingRun, *, create: bool = False) -> None: ...
    def get_training_run(self, run_id: str) -> TrainingRun: ...
    def save_backtest_run(self, run: BacktestRun, *, create: bool = False) -> None: ...
    def get_backtest_run(self, run_id: str) -> BacktestRun: ...
    def save_validation_run(self, run: ValidationRun, *, create: bool = False) -> None: ...
